### ISSUE TITLE
ES6 import AwaitQueue from 'awaitqueue'; does not work

### ISSUE THREAD

**Issue by ibc** [versatica/awaitqueue#1]
It should work given that the main module exports a class as follows:

```js
module.exports = AwaitQueue;
```

However, when using `browserify` + `babel` or `jest`, it fails with:

```
awaitqueue_1.default is not a constructor
```

**Comment by ibc** [comment]
Good explanation here: https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2

**Comment by jmillan** [comment]
The following option is required in `tsconfig.json`:

`"esModuleInterop": true`

**Comment by ibc** [comment]
Yeah, not a big here.
