### ISSUE TITLE
'awaitqueue' reports an error after upgrading to version 3. There is no problem with version 2.

### ISSUE THREAD

**Issue by panhezeng** [versatica/awaitqueue#9]
'awaitqueue' reports an error after upgrading to version 3. There is no problem with version 2.

ERROR in ./node_modules/mediasoup-client/node_modules/awaitqueue/lib/index.js 12:23
  Module parse failed: Unexpected token (12:23)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | class AwaitQueueStoppedError extends Error {
  |     constructor(message) {
  >         super(message ?? 'AwaitQueue stopped');
  |         this.name = 'AwaitQueueStoppedError';
  |         // @ts-ignore

**Comment by ibc** [comment]
Use a modern version of webpack or use a loader in webpack to load AwaitQueue and mediasoup-client libs. They use modern JavaScript ES. This is not a bug.

If you need help ask in the mediasoup forum (not here in GitHub).
